### ISSUE TITLE
Initial Installation via Helm Chart Failed

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#365]
**What happened**:
Deployment failed on first attempt via Helm.
```bash
➜ helm install hobbyfarm hobbyfarm/hobbyfarm --namespace hobbyfarm-system --values manifests/hf-values.yaml 
Error: INSTALLATION FAILED: 1 error occurred:
        * conversion webhook for hobbyfarm.io/v1, Kind=User failed: Post "https://hobbyfarm-webhook.hobbyfarm-system.svc:443/conversion/users.hobbyfarm.io?timeout=30s": no endpoints available for service "hobbyfarm-webhook"
```

On the second attempt, the deployment worked as expected.
```bash
➜ helm upgrade --install hobbyfarm hobbyfarm/hobbyfarm --namespace hobbyfarm-system --values manifests/hf-values.yaml
Release "hobbyfarm" has been upgraded. Happy Helming!
NAME: hobbyfarm
LAST DEPLOYED: Wed Oct  4 15:35:40 2023
NAMESPACE: hobbyfarm-system
STATUS: deployed
REVISION: 2
TEST SUITE: None
```

Here is the values.yaml file I used for deployment.
```yaml
gargantua:
  image: hobbyfarm/gargantua:v3.0.1-rc0
ingress:
  enabled: true
  tls:
    enabled: false
  hostnames:
    ui: ui.192-168-68-201.sslip.io
    admin: admin.192-168-68-201.sslip.io
    backend: hf.192-168-68-201.sslip.io
    shell: shell.192-168-68-201.sslip.io
insecure: true
users:
  admin:
    enabled: true
    password: $2a$10$9ToKMT37Z7K70xbCVnW9KOzEuPq0JyW/rA06gsukD4U9YfKFjMXTe
```

**What you expected to happen**:
Deployment via Helm to succeed on deployment.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
helm install hobbyfarm hobbyfarm/hobbyfarm --namespace hobbyfarm-system --values manifests/hf-values.yaml 
```

**Anything else we need to know?**:
This was the second time I had deployed HF on this environment via Helm. I deleted the previous installation via:
```bash
helm uninstall hobbyfarm
helm uninstall hf-provisioner-digitalocean
```

**Environment**:
- Gargantua version: hobbyfarm/gargantua:v3.0.1-rc0
- UI/Admin version: hobbyfarm/admin-ui:v3.0.0, hobbyfarm/ui:v3.0.0
- Kubernetes version (use `kubectl version`): K3s v1.27.6+k3s1
- Cloud provider or hardware configuration:
```bash
6-core CPU
64GB RAM
50GB Disk
```
- OS (e.g: `cat /etc/os-release`):
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
