### ISSUE TITLE
Dynamic proxy tabs with Proxy Settings

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#385]
**What would you like to be added**:
Dynamic proxy tabs with settings like Host Header Rewriting

**Why is this needed**:
I tried to install istio, istio creates gateways with dynamic ports and i proxying fails due to javascript files not being able to load due to a wrong root path. We need to enable host header rewriting

**Comment by jggoebel** [comment]
Could be implemented together with https://github.com/hobbyfarm/hobbyfarm/issues/286

Maybe add settings in the url, or in the cookies?

**Comment by jggoebel** [comment]
```css
.picture img{
   cursor: -moz-zoom-in;
   cursor: -webkit-zoom-in;
   cursor: zoom-in;
}
```
