### ISSUE TITLE
Add Magnifying glass Cursor when hovering images in markdown

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#386]
**What would you like to be added**:
If the user hovers over images change the cursor to magnifying glass

**Why is this needed**:
Images can be shown in a larger view, this is not clear when looking at the images or hovering over it

**Comment by jggoebel** [comment]
```css
.picture img{
   cursor: -moz-zoom-in;
   cursor: -webkit-zoom-in;
   cursor: zoom-in;
}
```
