### ISSUE TITLE
Adding users as instructed by documentation does not add the user

### ISSUE THREAD

**Issue by testmad** [boxboat/hobbyfarm-chart#444]
**What happened**:
Adding a user as shown in the documentation does not work. `user1` was added to the values.yaml and it was not created.

**What you expected to happen**:
`user1` to be created.

**How to reproduce it (as minimally and precisely as possible)**:
Add a user as shown in the documentation:
```
users:
  admin:
    enabled: false
    # default value to Sup3r@dmin
    password: $2a$10$9ToKMT37Z7K70xbCVnW9KOzEuPq0JyW/rA06gsukD4U9YfKFjMXTe
  user1:
    enabled: true
    # default value to Sup3r@dmin
    password: $2a$10$9ToKMT37Z7K70xbCVnW9KOzEuPq0JyW/rA06gsukD4U9YfKFjMXTe

```
Affects 3.2.1+

**Anything else we need to know?**:

**Environment**:
- Gargantua version:
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
